#
# Use this configuration file to control what RobotPy packages are installed
# on your RoboRIO
#

[tool.robotpy]

# Version of robotpy this project depends on
robotpy_version = "2025.2.1.0"

# Which extra RobotPy components should be installed
# -> equivalent to `pip install robotpy[extra1, ...]
robotpy_extras = [
    "phoenix6",
    "rev",
    "magicbot",
    "navx",
    "sim",
    "pathplannerlib",
    "apriltag",
    # "commands2"
    # "cscore"
    # "navx"
    # "phoenix5"
    # "phoenix6"
    # "playingwithfusion"
    # "rev"
    # "romi"
    # "sim"
    # "xrp"
]

# Other pip packages to install
requires = ["numpy", "limelightlib-python"]

[tool.pyright]
reportMissingTypeStubs = false
reportUninitializedInstanceVariable = false
